### ISSUE TITLE
Lower than 3 for "Max Vein Size" generates no ore at all

### ISSUE THREAD

**Issue by Atlntssplayer** [noahc3/oretweaker#7]
If I set 1 or 2 as the vein size in the config, no ore is generated at all.

"Max Vein Size" = 3 is the lowest when ore starts to appear.

This might be a Forge or Minecraft thing though, and not a bug in OreTweaker, because I read it from another mod author that the ore in his mod doesn't appear if the config in it has lower than 3.

But anyway, I just thought I mention this, because I noticed it while playing around with this great mod.

**Comment by noahc3** [comment]
I've verified I can generate ore with vein size 2. The random function is exclusive, so specifying a max of 5 actually means it will generate a vein of size 1-4. So with a max of 2, veins of up to size 1 are generated, and max of 1 means veins of size 0 are generated (aka no ore).

I'll tweak the configuration so that max vein size 1 actually means veins of size 1 can be generated.

**Comment by noahc3** [comment]
Included in v1.1.0
